export const homeOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Topline",
  headline: "Headline",
  description: "Description",
  buttonLabel: "Button",
  imgStart: false,
  img: require("../../images/bank4.svg").default,
  alt: "alt",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Topline",
  headline: "Headline",
  description: "Description",
  buttonLabel: "Button",
  imgStart: true,
  img: require("../../images/bank2.svg").default,
  alt: "alt",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeThree = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Topline",
  headline: "Headline",
  description: "Description",
  buttonLabel: "Button",
  imgStart: true,
  img: require("../../images/bank6.svg").default,
  alt: "alt",
  dark: true,
  primary: true,
  darkText: false,
};
